---
name: Nanobot
version: 0.1.4-2
slug: nanobot
description: Run Nanobot AI agent as a Home Assistant add-on
url: https://github.com/SeoFood/hassio-addons-nanobot/tree/main/nanobot
init: false
arch:
  - aarch64
  - amd64
startup: application
boot: auto
ports:
  18790/tcp: null
map:
  - share:rw
options:
  persistent_data_dir: nanobot
schema:
  persistent_data_dir: str
